// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCapjeodF-3IiJlfxqLAWK6K7P8LZV7fWE',
    appId: '1:271606453188:web:08427d40ba3a8700a2ca91',
    messagingSenderId: '271606453188',
    projectId: 'marvel-comics-app-777',
    authDomain: 'marvel-comics-app-777.firebaseapp.com',
    storageBucket: 'marvel-comics-app-777.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQAP6sCSVU0TrpKr4Mn824lXUwXhB6GFE',
    appId: '1:271606453188:android:835e68a213a394b4a2ca91',
    messagingSenderId: '271606453188',
    projectId: 'marvel-comics-app-777',
    storageBucket: 'marvel-comics-app-777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-GcP2JGdoKpLev8CJPSRvsFdW9_MZqv4',
    appId: '1:271606453188:ios:6b935f37d4cc715ca2ca91',
    messagingSenderId: '271606453188',
    projectId: 'marvel-comics-app-777',
    storageBucket: 'marvel-comics-app-777.appspot.com',
    iosClientId: '271606453188-apkmpdjvm616knhjkbikqkecl1pgqbir.apps.googleusercontent.com',
    iosBundleId: 'com.kubaolszewski.marvelComicsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-GcP2JGdoKpLev8CJPSRvsFdW9_MZqv4',
    appId: '1:271606453188:ios:6b935f37d4cc715ca2ca91',
    messagingSenderId: '271606453188',
    projectId: 'marvel-comics-app-777',
    storageBucket: 'marvel-comics-app-777.appspot.com',
    iosClientId: '271606453188-apkmpdjvm616knhjkbikqkecl1pgqbir.apps.googleusercontent.com',
    iosBundleId: 'com.kubaolszewski.marvelComicsApp',
  );
}
